export const people = [
  { name: "первый", text: "1", avatar: "", time: "10:49", unreadMes: 2 },
  {
    name: "Киноклуб",
    text: " sajkdnkasold askdljmasldk sak",
    avatar: "",
    time: "12:00",
  },
  {
    name: "Илья",
    text: "Друзья, у меня для вас особенный выпуск новостей! dkljdklas asldnalsdn asldnasd askdjkasd askdlkjasmd",
    avatar: "",
    time: "15:12",
    unreadMes: 4,
  },
  { name: "Андрей", text: "1", avatar: "", time: "10:49", unreadMes: 2 },
  {
    name: "Киноклуб",
    text: " sajkdnkasold askdljmasldk sak",
    avatar: "",
    time: "12:00",
  },
  {
    name: "Илья",
    text: "Друзья, у меня для вас особенный выпуск новостей! dkljdklas asldnalsdn asldnasd askdjkasd askdlkjasmd",
    avatar: "",
    time: "15:12",
    unreadMes: 4,
  },
  { name: "Андрей", text: "1", avatar: "", time: "10:49", unreadMes: 2 },
  {
    name: "Киноклуб",
    text: " sajkdnkasold askdljmasldk sak",
    avatar: "",
    time: "12:00",
  },
  {
    name: "Илья",
    text: "Друзья, у меня для вас особенный выпуск новостей! dkljdklas asldnalsdn asldnasd askdjkasd askdlkjasmd",
    avatar: "",
    time: "15:12",
    unreadMes: 4,
  },
  { name: "Андрей", text: "1", avatar: "", time: "10:49", unreadMes: 2 },
  {
    name: "Киноклуб",
    text: " sajkdnkasold askdljmasldk sak",
    avatar: "",
    time: "12:00",
  },
  {
    name: "Илья",
    text: "Друзья, у меня для вас особенный выпуск новостей! dkljdklas asldnalsdn asldnasd askdjkasd askdlkjasmd",
    avatar: "",
    time: "15:12",
    unreadMes: 4,
  },
  { name: "Андрей", text: "1", avatar: "", time: "10:49", unreadMes: 2 },
  {
    name: "Киноклуб",
    text: " sajkdnkasold askdljmasldk sak",
    avatar: "",
    time: "12:00",
  },
  {
    name: "Илья",
    text: "Друзья, у меня для вас особенный выпуск новостей! dkljdklas asldnalsdn asldnasd askdjkasd askdlkjasmd",
    avatar: "",
    time: "15:12",
    unreadMes: 4,
  },
  { name: "Андрей", text: "1", avatar: "", time: "10:49", unreadMes: 2 },
  {
    name: "Киноклуб",
    text: " sajkdnkasold askdljmasldk sak",
    avatar: "",
    time: "12:00",
  },
  {
    name: "Илья",
    text: "Друзья, у меня для вас особенный выпуск новостей! dkljdklas asldnalsdn asldnasd askdjkasd askdlkjasmd",
    avatar: "",
    time: "15:12",
    unreadMes: 4,
  },
  { name: "Андрей", text: "1", avatar: "", time: "10:49", unreadMes: 2 },
  {
    name: "Киноклуб",
    text: " sajkdnkasold askdljmasldk sak",
    avatar: "",
    time: "12:00",
  },
  {
    name: "Илья",
    text: "Друзья, у меня для вас особенный выпуск новостей! dkljdklas asldnalsdn asldnasd askdjkasd askdlkjasmd",
    avatar: "",
    time: "15:12",
    unreadMes: 4,
  },
  { name: "Андрей", text: "1", avatar: "", time: "10:49", unreadMes: 2 },
  {
    name: "Киноклуб",
    text: " sajkdnkasold askdljmasldk sak",
    avatar: "",
    time: "12:00",
  },
  {
    name: "Илья",
    text: "Друзья, у меня для вас особенный выпуск новостей! dkljdklas asldnalsdn asldnasd askdjkasd askdlkjasmd",
    avatar: "",
    time: "15:12",
    unreadMes: 4,
  },
  { name: "Андрей", text: "1", avatar: "", time: "10:49", unreadMes: 2 },
  {
    name: "Киноклуб",
    text: " sajkdnkasold askdljmasldk sak",
    avatar: "",
    time: "12:00",
  },
  {
    name: "Илья",
    text: "Друзья, у меня для вас особенный выпуск новостей! dkljdklas asldnalsdn asldnasd askdjkasd askdlkjasmd",
    avatar: "",
    time: "15:12",
    unreadMes: 4,
  },
  { name: "Андрей", text: "1", avatar: "", time: "10:49", unreadMes: 2 },
  {
    name: "Киноклуб",
    text: " sajkdnkasold askdljmasldk sak",
    avatar: "",
    time: "12:00",
  },
  {
    name: "Илья",
    text: "Друзья, у меня для вас особенный выпуск новостей! dkljdklas asldnalsdn asldnasd askdjkasd askdlkjasmd",
    avatar: "",
    time: "15:12",
    unreadMes: 4,
  },
  { name: "Андрей", text: "1", avatar: "", time: "10:49", unreadMes: 2 },
  {
    name: "Киноклуб",
    text: " sajkdnkasold askdljmasldk sak",
    avatar: "",
    time: "12:00",
  },
  {
    name: "Илья",
    text: "Друзья, у меня для вас особенный выпуск новостей! dkljdklas asldnalsdn asldnasd askdjkasd askdlkjasmd",
    avatar: "",
    time: "15:12",
    unreadMes: 4,
  },
  { name: "Андрей", text: "1", avatar: "", time: "10:49", unreadMes: 2 },
  {
    name: "Киноклуб",
    text: " sajkdnkasold askdljmasldk sak",
    avatar: "",
    time: "12:00",
  },
  {
    name: "Илья",
    text: "Друзья, у меня для вас особенный выпуск новостей! dkljdklas asldnalsdn asldnasd askdjkasd askdlkjasmd",
    avatar: "",
    time: "15:12",
    unreadMes: 4,
  },
  { name: "Андрей", text: "1", avatar: "", time: "10:49", unreadMes: 2 },
  {
    name: "Киноклуб",
    text: " sajkdnkasold askdljmasldk sak",
    avatar: "",
    time: "12:00",
  },
  {
    name: "Илья",
    text: "Друзья, у меня для вас особенный выпуск новостей! dkljdklas asldnalsdn asldnasd askdjkasd askdlkjasmd",
    avatar: "",
    time: "15:12",
    unreadMes: 4,
  },
  { name: "Андрей", text: "1", avatar: "", time: "10:49", unreadMes: 2 },
  {
    name: "Киноклуб",
    text: " sajkdnkasold askdljmasldk sak",
    avatar: "",
    time: "12:00",
  },
  {
    name: "Илья",
    text: "Друзья, у меня для вас особенный выпуск новостей! dkljdklas asldnalsdn asldnasd askdjkasd askdlkjasmd",
    avatar: "",
    time: "15:12",
    unreadMes: 4,
  },
  { name: "Андрей", text: "1", avatar: "", time: "10:49", unreadMes: 2 },
  {
    name: "Киноклуб",
    text: " sajkdnkasold askdljmasldk sak",
    avatar: "",
    time: "12:00",
  },
  {
    name: "Илья",
    text: "Друзья, у меня для вас особенный выпуск новостей! dkljdklas asldnalsdn asldnasd askdjkasd askdlkjasmd",
    avatar: "",
    time: "15:12",
    unreadMes: 4,
  },
  { name: "Андрей", text: "1", avatar: "", time: "10:49", unreadMes: 2 },
  {
    name: "Киноклуб",
    text: " sajkdnkasold askdljmasldk sak",
    avatar: "",
    time: "12:00",
  },
  {
    name: "Илья",
    text: "Друзья, у меня для вас особенный выпуск новостей! dkljdklas asldnalsdn asldnasd askdjkasd askdlkjasmd",
    avatar: "",
    time: "15:12",
    unreadMes: 4,
  },
  { name: "Андрей", text: "1", avatar: "", time: "10:49", unreadMes: 2 },
  {
    name: "Киноклуб",
    text: " sajkdnkasold askdljmasldk sak",
    avatar: "",
    time: "12:00",
  },
  {
    name: "Илья",
    text: "Друзья, у меня для вас особенный выпуск новостей! dkljdklas asldnalsdn asldnasd askdjkasd askdlkjasmd",
    avatar: "",
    time: "15:12",
    unreadMes: 4,
  },
  { name: "Андрей", text: "1", avatar: "", time: "10:49", unreadMes: 2 },
  {
    name: "Киноклуб",
    text: " sajkdnkasold askdljmasldk sak",
    avatar: "",
    time: "12:00",
  },
  {
    name: "ПОСЛЕДНИЙ",
    text: "Друзья, у меня для вас особенный выпуск новостей! dkljdklas asldnalsdn asldnasd askdjkasd askdlkjasmd",
    avatar: "",
    time: "15:12",
    unreadMes: 4,
  },
];
